#!/usr/bin/env bash

dbus-update-activation-environment --systemd DISPLAY

function set-xkb-shit() {
	setxkbmap -layout us,ru -option grp:win_space_toggle,compose:ralt
}

set-xkb-shit

while :; do # :face_with_bags_under_eyes:
	xinput watch-props 1 >/dev/null 2>&1 || sleep 2
	set-xkb-shit
	sleep 1
done &

clipcatd
x0vncserver -interface 10.69.69.69 & # so i can code on this bitch from work

dunst &
# TODO: run a taskbar
flameshot &
sunshine & # so i can game on this bitch from work
steam -silent &

v2rayN &
telegram-desktop &
