#!/bin/bash

emoji=💽

avail=`df -BG | awk '/sda1/ { print $4 }'`
avail=${avail::-1}

format="$emoji $avail GB"

echo "$format"
echo "$format"

[ `expr $avail "<" 18` = 1 ] && echo `xrdb -query | grep -m1 color3 | cut -f2`
[ `expr $avail "<" 10` = 1 ] && echo `xrdb -query | grep -m1 color1 | cut -f2` \
                             || echo `xrdb -query | grep -m1 color2 | cut -f2`
