#!/bin/bash

avail=`df -BG | awk '/sda1/ { print $4 }'`
avail=${avail::-1}

format="$avail GB"

ok=`xrdb -query | grep -m1 color2 | cut -f2`
low=`xrdb -query | grep -m1 color3 | cut -f2`
meh=`xrdb -query | grep -m1 color1 | cut -f2`

[ `expr $avail \< 18` = 1 ] && color=$low
[ `expr $avail \< 10` = 1 ] && color=$meh \
                            || color=$ok

echo "%{F$color}$format"
