#!/bin/sh

ip=`ip a s ppp0 | awk '/inet[^6]/ { print $2 }'`
up=`xrdb -query | grep -m1 color2 | cut -f2`
down=`xrdb -query | grep -m1 color1 | cut -f2`

echo -n "ppp0: "
[ "$ip" ] && echo "%{F$up}$ip" \
          || echo "%{F$down}down"
