# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# reload config
bind=SUPER+SHIFT,r,reload_config

# menu and terminal
bind=SUPER,r,spawn,bemenu-run
bind=SUPER,Return,spawn,footclient

# labwc ports
bind=SUPER,bracketleft,spawn,volumectl lower
bind=SUPER,bracketright,spawn,volumectl raise
bind=NONE,XF86AudioLowerVolume,spawn,volumectl lower
bind=NONE,XF86AudioRaiseVolume,spawn,volumectl raise
bind=SUPER,v,spawn_shell,cliphist list | bemenu | cliphist decode | wl-copy
bind=NONE,Print,spawn,flameshot gui -c
bind=SHIFT,Print,spawn,flameshot full -c
bind=ALT,Print,spawn,flameshot full -c

# exit
bind=SUPER+SHIFT,m,quit
bind=ALT,q,killclient,

# switch window focus
bind=SUPER,Tab,focusstack,next
bind=SUPER,h,focusdir,left
bind=SUPER,l,focusdir,right
bind=SUPER,j,focusdir,up
bind=SUPER,k,focusdir,down

# swap window
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,l,exchange_client,right

# switch window status
bind=SUPER,g,toggleglobal,
bind=ALT,Tab,togglejump,
bind=SUPER,backslash,togglefloating,
bind=SUPER,a,togglemaximizescreen,
bind=SUPER,f,togglefullscreen,
bind=SUPER+SHIFT,f,togglefakefullscreen,
bind=SUPER,i,minimized,
bind=SUPER,o,toggleoverlay,
bind=SUPER+SHIFT,I,restore_minimized
#bind=SUPER,z,toggle_scratchpad

# scroller layout
bind=SUPER,e,set_proportion,1.0
bind=SUPER,x,switch_proportion_preset,
bind=SUPER+CTRL,h,scroller_stack,left
bind=SUPER+CTRL,l,scroller_stack,right
bind=SUPER+CTRL,k,scroller_stack,up
bind=SUPER+CTRL,j,scroller_stack,down

#dwindle layout(manual split mode)
bind=alt+shift,Return,dwindle_toggle_split_direction

# switch layout
bind=SUPER,n,switch_layout

# tag switch
#bind=SUPER,Left,viewtoleft,0
#bind=CTRL,Left,viewtoleft_have_client,0
#bind=SUPER,Right,viewtoright,0
#bind=CTRL,Right,viewtoright_have_client,0
#bind=CTRL+SUPER,Left,tagtoleft,0
#bind=CTRL+SUPER,Right,tagtoright,0

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
# bind=Alt,1,tagsilent,1
#bind=Alt,1,tag,1,0
#bind=Alt,2,tag,2,0
#bind=Alt,3,tag,3,0
#bind=Alt,4,tag,4,0
#bind=Alt,5,tag,5,0
#bind=Alt,6,tag,6,0
#bind=Alt,7,tag,7,0
#bind=Alt,8,tag,8,0
#bind=Alt,9,tag,9,0

# monitor switch
#bind=alt+shift,Left,focusmon,left
#bind=alt+shift,Right,focusmon,right
#bind=SUPER+Alt,Left,tagmon,left
#bind=SUPER+Alt,Right,tagmon,right

# gaps
#bind=ALT+SHIFT,X,incgaps,1
#bind=ALT+SHIFT,Z,incgaps,-1
bind=SUPER+ALT,R,togglegaps

# movewin
bind=SUPER+ALT,k,movewin,+0,-50
bind=SUPER+ALT,j,movewin,+0,+50
bind=SUPER+ALT,h,movewin,-50,+0
bind=SUPER+ALT,l,movewin,+50,+0

# resizewin
#bind=CTRL+ALT,Up,resizewin,+0,-50
#bind=CTRL+ALT,Down,resizewin,+0,+50
#bind=CTRL+ALT,Left,resizewin,-50,+0
#bind=CTRL+ALT,Right,resizewin,+50,+0

bind=SUPER,q,killclient

# Mouse Button Bindings
# btn_left and btn_right can't bind none mod key
mousebind=SUPER,btn_left,moveresize,curmove
#mousebind=NONE,btn_middle,togglemaximizescreen,0
mousebind=SUPER,btn_right,moveresize,curresize
mousebind=SUPER,btn_middle,killclient

# Axis Bindings
#axisbind=SUPER,UP,viewtoleft_have_client
#axisbind=SUPER,DOWN,viewtoright_have_client

# layer rule
#layerrule=animation_type_open:zoom,layer_name:rofi
#layerrule=animation_type_close:zoom,layer_name:rofi
