exec_once=xsettingsd

#exec-once=wlsunset -l 55.9 -L 43.0
exec_once=wl-paste --watch cliphist store
#exec-once=wl-clip-persist --clipboard regular
exec_once=wayvnc :: # so i can code on this bitch from work
exec_once=swaybg -m fill -i ~/.wallpaper.jpg

exec_once=dunst
exec_once=waybar
exec_once=flameshot
exec_once=sunshine # so i can game on this bitch from work

exec_once=steam -silent
exec_once=telegram-desktop
exec_once=v2rayN
