#exec-once=wlsunset -l 55.9 -L 43.0 &
exec-once=wl-paste --watch cliphist store &
exec-once=wayvnc 10.69.69.69 100.64.0.2 & # so i can code on this bitch from work

exec-once=dunst
exec-once=waybar
exec-once=flameshot
exec-once=sunshine # so i can game on this bitch from work
exec-once=steam -silent

exec-once=foot --server

exec-once=v2rayN
exec-once=telegram-desktop
