#exec-once=wlsunset -l 55.9 -L 43.0
exec-once=wl-paste --watch cliphist store
#exec-once=wl-clip-persist --clipboard regular
exec-once=wayvnc 10.69.69.69 home # so i can code on this bitch from work
exec-once=swaybg -m fill -i ~/.wallpaper.jpg

exec-once=dunst
exec-once=waybar
exec-once=flameshot
exec-once=foot --server
exec-once=sunshine # so i can game on this bitch from work

exec-once=steam -silent
exec-once=telegram-desktop
exec-once=v2rayN
