# More option see https://github.com/DreamMaoMao/mango/wiki/

auto_reload_config=1

# Window effect
blur=0
blur_layer=0
blur_optimized=1
blur_params_num_passes = 2
blur_params_radius = 5
blur_params_noise = 0.02
blur_params_brightness = 0.9
blur_params_contrast = 0.9
blur_params_saturation = 1.2

shadows=0
layer_shadows=0
shadow_only_floating=1
shadows_size=10
shadows_blur=15
shadows_position_x=0
shadows_position_y=0
shadows_color=0x000000ff

border_radius=0
no_radius_when_single=0
focused_opacity=1.0
unfocused_opacity=1.0

# Animation Configuration(support type:zoom,slide)
# tag_animation_direction: 1-horizontal,0-vertical
animations=1
layer_animations=1
animation_type_open=slide
animation_type_close=slide
animation_fade_in=1
animation_fade_out=1
tag_animation_direction=1
zoom_initial_ratio=0.4
zoom_end_ratio=0.8
fade_in_begin_opacity=0.5
fade_out_begin_opacity=0.8
animation_duration_move=500
animation_duration_open=400
animation_duration_tag=350
animation_duration_close=800
animation_duration_focus=0
animation_curve_open=0.46,1.0,0.29,1
animation_curve_move=0.46,1.0,0.29,1
animation_curve_tag=0.46,1.0,0.29,1
animation_curve_close=0.08,0.92,0,1
animation_curve_focus=0.46,1.0,0.29,1
animation_curve_opacity_fade_out=0.5,0.5,0.5,0.5
animation_curve_opacity_fade_in=0.46,1.0,0.29,1

# Scroller Layout Setting
scroller_structs=20
scroller_default_proportion=1.0
scroller_focus_center=0
scroller_prefer_center=0
edge_scroller_pointer_focus=1
edge_scroller_focus_allow_speed=0.0
scroller_default_proportion_single=1.0
scroller_proportion_preset=0.5,0.8,1.0

# Master-Stack Layout Setting
new_is_master=1
default_master_factor=0.55
default_master_count=1
smart_gaps=0

# Dwindle Layout Setting
dwindle_smart_split=0
dwindle_drop_simple_split=1
dwindle_manual_split=0
dwindle_horizontal_split=1
dwindle_vertical_split=1
dwindle_preserve_split=0

# Overview Setting
hotarea_size=10
enable_hotarea=0
ov_tab_mode=0
overview_gap_inner=5
overview_gap_outer=30

# Misc
no_border_when_single=0
axis_bind_apply_timeout=100
focus_on_activate=0 # prevents autofocus on windows sending notifications
idle_inhibit_ignore_visible=0
sloppy_focus=1
warp_cursor=1
focus_cross_monitor=0
focus_cross_tag=0
enable_floating_snap=0
snap_distance=30
drag_tile_to_tile=1
drag_tile_small=1

# keyboard
repeat_rate=30
repeat_delay=200
numlock_on=1
xkb_rules_layout=us,ru
xkb_rules_options=grp:win_space_toggle,compose:ralt

# mouse
disable_middle_paste=1
# need relogin to make it apply
mouse_natural_scrolling=0

# Appearance
gap_inner_horizontal=0
gap_inner_vertical=0
gap_outer_horizontal=0
gap_outer_vertical=0
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
border_px=2
root_color=0x201b14ff
border_color=0x444444ff
drop_color=0x8FBA7C55
split_color=0xEB441EFF
focus_color=0x2f343fff
maximized_screen_color=0x89aa61ff
urgent_color=0xad401fff
scratchpad_color=0x516c93ff
global_color=0xb153a7ff
overlay_color=0x14a57cff
monocle_no_gap=1
monocle_no_border=1

# :drooling_face:
cursor_size=24
cursor_theme=jue13
