tag_rule=id:1,layout_name:monocle
tag_rule=id:2,layout_name:monocle
tag_rule=id:3,layout_name:monocle
tag_rule=id:4,layout_name:monocle
tag_rule=id:5,layout_name:monocle
tag_rule=id:6,layout_name:monocle
tag_rule=id:7,layout_name:monocle
tag_rule=id:8,layout_name:monocle
tag_rule=id:9,layout_name:monocle

window_rule=is_floating:1,app_id:flameshot,title:flameshot
window_rule=animation_type_open:none,app_id:flameshot,title:flameshot
window_rule=animation_type_close:none,app_id:flameshot,title:flameshot

allow_tearing=2
