tagrule=id:1,layout_name:monocle
tagrule=id:2,layout_name:monocle
tagrule=id:3,layout_name:monocle
tagrule=id:4,layout_name:monocle
tagrule=id:5,layout_name:monocle
tagrule=id:6,layout_name:monocle
tagrule=id:7,layout_name:monocle
tagrule=id:8,layout_name:monocle
tagrule=id:9,layout_name:monocle

windowrule=isfloating:1,appid:flameshot,title:flameshot
windowrule=animation_type_open:none,appid:flameshot,title:flameshot
windowrule=animation_type_close:none,appid:flameshot,title:flameshot

allow_tearing=2
