tagrule=id:1,layout_name:monocle
tagrule=id:2,layout_name:tile

windowrule=isfloating:1,appid:flameshot,title:flameshot
windowrule=animation_type_open:none,appid:flameshot,title:flameshot
windowrule=animation_type_close:none,appid:flameshot,title:flameshot

allow_tearing=2
