library: ~/.config/beets/library.db

plugins: fetchart embedart lastgenre replaygain lyrics duplicates mpdupdate

fetchart:
  auto: no

lyrics:
  auto: no

lastgenre:
  auto: no

replaygain:
    backend: gstreamer
    overwrite: yes

import:
  move: yes
