directory: /media/hdd/Music
plugins: >-
  fetchart embedart lastgenre replaygain duplicates missing lyrics mbsync lidarrfields
paths:
  default: $releasegroupartist/$lidarralbum ($year)/%if{$audiodisctotal,$disc - }${track}. $title
  comp: Various Artists/$lidarralbum ($year)/%if{$audiodisctotal,$disc - }${track}. $title
per_disc_numbering: yes
lyrics:
  auto: yes
  sources: musixmatch genius google
lastgenre:
  auto: yes
  count: 10
  separator: ;
replaygain:
  auto: no
  backend: command
